const CYBERSECURITY = {
    "internal threat": "An employee stealing company data could be an example of which kind of threat actor?",
    "hacker": "A general term used to describe any individual who uses their technical knowledge to gain unauthorized access to an organization",
    "script kiddie": "an individual who carries out an attack by using scripts or programs written by more advanced hackers",
    "opportunistic attack": "A hacker scans hundreds of IP addresses randomly on the internet until they find an exploitable target. What kind of attack is this?",
    "staging": "Preparing a computer to perform additional tasks in the attack",
    "reconnaissance": "the process of gathering information about an organization, including system hardware information, network configuration, and individual user information",
    "layering": "the process of implementing multiple security measures to protect the same asset",
    "reconnaissance": "which phase of an attack does the attacker gather information about the target?",
    "confidentiality": "ensures that data is not disclosed to unintended persons",
    "cyber terrorists": "these people generally use the internet to carry out activities such as disrupting network-dependent institutions",
    "non-repudiation": "The ability to prove that a sender undeniably sent a message",
    "privacy": "the protection and confidentiality of personal information",
    "integrity": "protection against alteration",
    "application layer": "this layer of the security model includes user management and web application security",
    "host layer": "this layer of the security model includes log management",
    "physical layer": "this layer of the security model includes environmental controls",
    "data layer": "this layer of the security model includes cryptography",
    "perimeter layer": "this layer of the security model includes securing firewalls",
    "employees": "the single greatest threat to network security",
    "network layer": "this layer of the security model includes penetration testing",
    "botnet": "A collection of zombie computers have been set up to collect personal information. Which type of malware do the zombie computers represent?",
    "fileless virus": "this kind of virus operates only in memory and usually exploits a trusted application like PowerShell to circumvent traditional endpoint security solutions",
    "worm": "a self-replicating program",
    "ransomware": "A type of malware that prevents the system from being used until the victim pays the attacker money",
    "remote access trojan": "this kind of malware provides an attacker with administrative control over a target computer through a backdoor",
    "spyware": "monitors the actions you take on your machine and sends the information back to its originating source",
    "Trojan horse": "a malicious program disguised as legitimate software",
    "virus": "a program that attempts to damage a computer system and replicate itself to other computer systems",
    "social engineering": "Any attack involving human interaction of some kind",
    "social engineering": "Keylogging, impersonation, and shoulder surfing are all examples of this type of attack",
    "super user account": "The root account has all privileges and no barriers. Also known as...",
    "data breach": "when confidential or protected data is exposed",
    "PTZ": "this camera type lets you dynamically move and zoom in on specific areas",
    "technical control": "Passwords, access control lists, and smart cards are all examples of...",
    "administrative control": "Requiring background checks for hiring is an example of a policy or...",
    "piggybacking": "when an authorized or unauthorized individual gains entry into a secured area by exploiting the credentials of a prior person",
    "recovery": "the phase after a breach has occurred in which damage from the event is repaired and a review is made to determine what should be done to prevent future incidents of the same nature",
    "smart card": "access control technology that allows more than just the identity of an individual to be transmitted wirelessly, to either allow or deny access",
    "demilitarized zone": "provides enhanced security by isolating your publicly accessible network from your privately accessible network",
    "air gap": "a security method that physically isolates a portion of the network (such as a computer, a server, or a small network of computers) from the internet or any other unsecured networks",
    "electromagnetic emissions": "Faraday cages are designed to block all...",
    "cable lock": "the best protection against the physical theft of laptops is the placement of a...",
    "locked room": "To control access to the router console, you must keep the router in a...",
    "paper": "Burning, pulping (using water or chemicals), and shredding are three ways to securely dispose of data in which form?",
    "air gap": "A computer or small network that is not connected to the rest of the network or the internet is known as...",
    "USB data blocker": "used to allow a USB device to charge but blocks the data transfer capabilities of the device",
    "demilitarized zone": "an area of the network where extra security is placed to protect the internal network from publicly accessible servers like web servers and email servers",
    "electromagnetic interference": "it is important to follow correct procedures when running electrical cables next to data cables in order to protect against this environmental concern...",
    "hot aisle": "where all of the heat is sent from the servers and network equipment to be transmitted to the HVAC return vent",
    "infrastructure": "power, heating, ventilation, air conditioning systems (HVAC), and utilities are all components of...",
    "uninterruptible power supply": "provides continuous power using batteries for a short period of time, often paired with a backup generator",
    "packet sniffing": "the process of capturing data packets that are flowing across the network and analyzing them for important information",
    "ping": "a command line tool that is used to perform a connection test between two network devices",
    "traceroute": "a tool that shows the path a packet takes to reach its destination",
    "ipconfig": "command tool used to display the IP configuration on the local computer",
    "gain access": "the third phase of the penetration test life cycle; uses the information gathered in earlier phases to exploit discovered vulnerabilities",
    "maintain access": "Which step in the penetration testing life cycle is accomplished using rootkits or Trojan horse programs?",
    "blue team": "team members on the defense of the system",
    "red team": "ethical hacker team performing penetration tests",
    "penetration testing": "the practice of proactively testing systems and policies for vulnerabilities",
    "dig": "Linux tool command that can be used to look up DNS server information and give IP addresses and domain names for a network server",
    "route": "a tool command used in both Windows and Linux to show the routing table and to make manual changes to it",
    "network mapper": "a tool that can discover devices on a network and show those devices in a graphical representation",
    "ping": "a command used to perform a connection test by sending ICMP packets to a specified device on a network and then wait for a response",
    "nmap": "an open-source security scanner used for network enumeration and the creation of network maps",
    "war driving": "the act of searching for wireless networks (802.11) using a signal detector or a network client",
    "false positive": "occur when a scan says there is a vulnerability, but there is none",
    "false negative": "occur when the scanner misses a vulnerability",
    "true negative": "occur when the scanner says there are no vulnerabilities and there are none",
    "true positive": "occur when the scanner shows a vulnerability that does exist",
    "vulnerability scanner": "a tool to gather information about systems such as the applications or services running on a system",
    "port scanner": "used to check for open ports on a system or firewall",
    "spoofing": "the technique of falsifying the source address in a packet",
    "antivirus software": "the most common form of host-based IDS that employs signature or pattern-matching detection methods",
    "procedures layer": "layer: user education; manage network plans; employee onboarding and off-boarding",
    "physical layer": "layer: fences, door locks, mantraps, server cages, cameras, and environmental controls",
    "perimeter layer": "layer: firewalls using ACLs and securing the wireless network",
    "network layer": "layer: the installation and configuration of switches and routers; implementation of VLANs; pen testing; virtualization use",
    "host layer": "layer: log management, OS hardening, patch implementation, auditing, anti-malware, and password attack prevention",
    "application layer": "layer: authentication and authorization, user management, group policies, and web security",
    "data layer": "layer: storage and handling of data, cryptography, and data transmission security",
    "access control list": "network traffic filters that control incoming and outcoming traffic; stateless firewall",
    "capture filter": "records the frames from a specified IP address identified by a filter",
    "firewalking": "uses the traceroute command to discover which services can pass through a firewall or router",
    "port scanning": "pings every port on an external interface or attempts a connection in order to discover which ports are open and active, and which ones are not",
    "fingerprinting": "identifies which operating system the system is running based on how it responds to different types of network traffic",
    "protocol analyzer": "identify traffic that is generated and sent through a network by a specific application running on a device; packet sniffer",
    "packet sniffer": "to monitor network traffic and sort traffic by protocol; protocol analyzer",
    "packet sniffer": "a special software that captures (records) frames transmitted on the network; protocol analyzer",
    "protocol analyzer": "Wireshark is a popular packet sniffer aka a...",
    "ARP poisoning": "when an attacker sends falsified messages to link their MAC address with the IP address of a legitimate computer or server on a network",
    "port mirroring": "creates a duplicate of all network traffic on a port and sends it to another device",
    "MAC flooding": "when an attacker intentionally floods a content-addressable memory table with Ethernet frames, each originating from different MAC addresses",
    "MAC spoofing": "to enable the bypass of access control lists on servers or routers by either hiding a computer on a network or by allowing it to impersonate another network device",
    "ARP poisoning": "an attack that tries to associate an incorrect MAC address with a known IP address",
    "DNS poisoning": "when a name server receives malicious or misleading data that incorrectly maps host names and IP addresses",
    "man in the middle": "a false server intercepts communications from a client by impersonating the intended server",
    "spoofing": "changes or falsifies information in order to mislead or re-direct traffic",
    "brute force": "this technique tests every possible keystroke for each single key in a password until the correct one is found",
    "password salting": "adding random bits of data to a password before it is stored as a hash, making password cracking much more difficult",
    "security incident": "a violation of a security policy",
    "audit trail": "to detect security-violating events or actions",
    "documentation": "the first step after an intrusion is to retain the...",
    "Cyber Kill Chain": "exists to provide visibility to the hurdles of a malicious actor and make it easier to defend your assets",
    "content filtering": "a strategy to keep employees from accessing unauthorized content on the web",
    "mobile device management": "offers a way to remotely monitor, manage, and wipe mobile devices",
    "whitelisting": "this application endpoint-protection rule implicitly denies network access unless added to the rule.",
    "blacklisting": "lists the applications, IP addresses, URLs, email addresses, etc. that are to be blocked from the network",
    "runbook": "a condition-based series of protocols you can use to establish automated processes for security-incident response",
    "playbook": "a checklist style document that specifies the steps to be taken in response to a threat or incident",
    "containment": "You have detected and identified a security event. What's the first step you should complete?",
    "segmentation": "You need to limit the impact of a security breach for a particular file server with sensitive company data. Which strategy would you employ?",
    "isolation": "You need to limit a compromised application from causing harm to other assets in your network. Which strategy should you employ?",
    "segmentation": "a strategic network design to keep the sections of a network separated so that malicious actors cannot pivot within a network.",
    "SOAR": "this compiled information is sent to a security analyst for further action (Security Orchestration, Automation, and Response)",
    "SIEM": "a software tool used to compile and examine multiple data points gathered from across a network (Security Information and Event Management)",
    "alerts": "Which component of the SIEM lets the IT team know that a pre-established parameter is not within the acceptable range?",
    "sensors": "programmed to send customized alerts to the SIEM if certain parameters are not within the acceptable range",
    "trends": "patterns of activity discovered and reported to the SIEM",
    "application log": "these logs show application access, crashes, updates, and any other relevant information that could be valuable in conducting a root cause analysis",
    "dump files": "these files are created when an application, OS, or other computer function stops abruptly",
    "syslog": "a standard, or protocol, for sending log messages to a central logging server",
    "nmap": "a network mapping tool that performs ping and port scans",
    "system log": "this log records operating system, system, and hardware events",
    "web server log": "this log, although tedious to parse, can tell you exactly when users log onto your site and what their location is",
    "x-headers": "What can be put throughout an email's header that provides the originating email account or IP address and not a spoofed one?",
    "chain of custody": "What is the most important element related to evidence in addition to the evidence itself?",
    "chain of custody": "a document related to evidence-gathering that contains details about personnel in possession and control of evidence from the time of discovery up through the time of presentation in court",
    "hashing": "it's purpose is to detect the alteration of the log file",
    "hashing": "the method used to verify that a bit-level image copy of a hard drive is an exact clone of the original hard drive collected as evidence",
    "grep": "this Linux command searches through files for a specified character string",
    "head": "this Linux command shows the first few lines of a file",
    "chmod": "this Linux command assigns or removes permissions to users, groups, or others",
    "tail": "this Linux command shows the last few lines of a file",
    "logger": "this Linux command lets you add entries in the system log file",
    "cat": "this Linux command lists the contents of a file",
    "MAC spoofing": "allows an attacker's computer to connect to a switch using an authorized MAC address",
    "MAC flooding": "the process of intentionally overwhelming the CAM table with Ethernet frames, each originating from a different MAC address",
    "ARP poisoning": "the MAC address of the attacker can be associated with the IP address of another host",
    "port mirroring": "creates a duplicate of all network traffic on a port and sends it to another device",
    "cold site": "a recovery site that may have electricity connected, but there are no servers installed and no high-speed data lines present",
    "hot site": "a real-time full mirror of the primary site, functional and ready to use 24/7",
    "warm site": "a remote network location that maintains a backup of the data, but it is not always current",
    "redundancy": "the primary security feature that can be designed into a network's infrastructure to protect and support availability",
    "clustering": "the connection of multiple servers together so that if one server fails, the others immediately take over its tasks, preventing a disruption in service",
    "service level agreement": "a contract that prescribes the technical support or business parameters a provider bestows to its client",
    "final audit report": "the result of an external auditor's inspection and analysis of an organization's security status",
    "certificate practice statement": "defines the actions and promises of a certificate service authority",
    "mutual aid agreement": "an agreement between two organizations to support each other in the event of a disaster",
    "service level agreement": "a guarantee of a specific level of service from a vendor; SLA",
    "blanket purchase order": "an agreement with a third-party vendor to provide services on an ongoing basis; BPO",
    "altered": "management of change control is necessary any time a production system is...",
    "change control": "used to maintain the current level of security and prevent changes from diminishing that security",
    "residual risk": "the portion of risk that remains after the implementation of a countermeasure",
    "exposure": "the vulnerability of losses from a threat agent, and risk is the likelihood of a vulnerability being exploited",
    "SMTP relay": "an email server that accepts mail and forwards it to other mail servers",
    "email security gateway": "a security solution that monitors emails that are sent to or originate from an organization",
    "email encryption": "digitally signs an email with a certificate providing a form of identity verification",
    "phishing": "a fraudulent email that claims to be from a trusted organization",
    "SMTP server": "attackers often distribute spam by hijacking a misconfigured...",
    "spam": "numerous unwanted and unsolicited email messages being sent to a wide range of victims",
    "confidentiality": "A user copies files from her desktop computer to a USB flash device and puts the device into her pocket. Which security risk is most pressing?",
    "cyber terrorists": "disrupts network-dependent institutions",
    "integrity": "hashing of any sort, including within a digitial signature, provides data...",
    "internal threat": "A user accidentally deletes the new product designs.",
    "physical security": "all hardware and software necessary to secure data, such as firewalls and antivirus software",
    "confidentiality, integrity, availability": "The three main goals of security (CIA)",
    "threat": "any potential danger to the confidentiality, integrity, or availability of information systems",
    "vulnerability": "the absence or weakness of a safeguard that could be exploited",
    "backdoor": "an unprotected entry into a device or system",
    "encryption": "the process of using an algorithm or other method to transform data from plaintext to a difficult-to-interpret cipher text",
    "IDS": "used to detect failures and deficiencies in a firewall; a complimentary product to a firewall; intrusion detection system",
    "incremental backup": "a backup method that copies to tape only those files that have not been marked previously",
    "Kerberos": "an authentication encryption protocol designed to provide security for the initial logon process and service requests; uses symmetric key cryptography",
    "key clustering": "a vulnerability in encryption that occurs when the same message, encrypted with different keys, results in the same cipher text",
    "layering": "when various tasks are divided into a hierarchial manner to provide security",
    "logic bomb": "a program that performs a malicious activity at a specific time or after a triggering event",
    "port scanning": "a specialized method of system scanning that probes all TCP/UDP ports to identify which are open",
    "site survery": "designed to determine how wireless technologies will function within a specific area and what will be required to optimize performance and reliability",
    "SMTP relay": "an e-mail server that is configured to forward e-mail from one system to another",
    "sniffing": "a common network monitoring or diagnostic activity that can be used as a passive malicious attack; duplcates the packets it sees without altering flow",
    "spoofing": "the act of changing or falsifying information in order to mislead or re-direct traffic",
    "subkey": "referred to as a session key or temporary key",
    "system scanning": "vulnerability scanning and penetration testing are both types of...",
    "rootkit": "a set of software tools that enable an unauthorized user to gain control of a computer system without being detected.",
    "asset": "something that has value to an individual or organization",
    "threat actor": "the person or entity that carries out a threat; also a threat agent",
    "exploit": "to take advantage of a vulnerability and carry out an attack",
    "application layer": "this security layer includes user management and web application security",
    "script kiddies": "keeping systems up to date and using standard security practices is the best defense against...",
    "exploitation": "crashing systems is a form of...",
    "rootkit": "a set of programs residing below regular antivirus software detection which requires administrator-level privileges for installation",
    "physical access control": "Which security control, if not applied, can allow an attacker to bypass other security controls?",
    "data exfiltration": "DNS tunneling is a common method that allows an attacker to accomplish which attack?",
    "DNS tunneling": "a method that allows an attacker to hide data being sent to an outside host by disguising it as DNS traffic",
    "identity theft": "when an attacker uses information gained from a data breach to commit fraud by doing things like opening new accounts with the victim's information",
    "reconnaissance": "Which phase or step of a security assessment is a passive activity?",
    "nmap": "an open-source security scanner used for network enumeration and the creation of network maps",
    "OSINT": "Gathering as much personally identifiable information (PII) on a target as possible is a goal of which reconnaissance method?",
    "OSINT": "any data that is collected from publicly available sources (open-source intelligence)",
    

};
