const JAVATERMS = {
    "(true/false): All Java variables must be declared with a name and a type before they can be used.": "true",
    "(true/false): Any fractional part in integer division in simply rounded to the next highest number.": "false",
    "Write a method for the absolute value of x": "abs(x)",
    "Write a method that rounds x to the smallest integer not less than x": "ceil(x)",
    "Wrte a method for the trigonometric cosine of x": "cos(x)",
    "Write a method for the exponential of x": "exp(x)",
    "A location in the computer's memory where a value can be stored for use later in a program.": "variable",
    "Regardless of difference in physical appearance, computers can be envisioned as divided into sections or various...": "logical units",
    "This statement, when executed in a while, for, do..while or switch, causes immediate exit from that statement": "break",
    "Methods of the same name can be declared in the same class, as long as they have different sets of parameters. This is called...": "method overloading",
    "Specifying the order in which statements (actions) execute in a program": "program control",
    "Specifies what kind of information is stored at that location in memory.": "variable type",
    "Several related fields can be used to compose a...": "record",
    "Computers process data under the control of sequences of instructions called...": "computer programs",
    "Just as class may contain static methods, a class also may contain static variables. These are called...": "class variables",
    "A group of characters or bytes that convey a meaning": "field",
    "false || false": "false",
    "false || true": "true",
    "true || true": "true",
    "true || false": "true",
    "false && false": "false",
    "false && true": "false",
    "true && false": "false",
    "true && true": "true",
    "printf character": "%c",
    "printf decimal (integer) number (base 10)": "%d",
    "printf exponential floating-point number": "%e",
    "printf floating-point number": "%f",
    "printf integer (base 10)": "%i",
    "printf octal number (base 8)": "%o",
    "printf string of characters": "%s",
    "printf unsigned decimal (integer) number": "%u",
    "printf number in hexadecimal (base 16)": "%x",
    "printf percent sign (or \\%)": "%%",
    "printf backspace": "\\b",
    "printf newline, or linefeed": "\\n",
    "printf carriage return": "\\r",
    "printf tab": "\\t",
    "(T/F): A variable name must contain a letter, number, underscore, and dollar sign and it cannot begin with a digit. ": "false",
    "(T/F): Real numbers contain decimal points, such as in 3.4 and -11.9.": "true",
    "Primitive type: character data": "char",
    "Primitive type: integer values": "int",
    "Primitive type: real numbers": "float",
    "Primitive type: true/false": "boolean",
    "Type the assignment statement that will read user input (\"input\") and assigns it to integer variable num1": "num1 = input.nextInt();",
    "When executed in a while, for,or do..while, skips the remaining statement in the loop body and proceeds with the next iteration of the loop.": "continue",
    "A procedure for solving a problem in terms of the action to execute and the order in which these actions execute": "algorithm",
    "The escape sequence key \"horizontal tab\" is denoted by...": "\\t",
    "Comma-separated and located in the parenthesis that follow the method name": "parameter list",
    "Single selection statement that performs an indicated action only when the condition is true; otherwise, the action is skipped.": "if",
    "An expression that can be true or false. ": "condition",
    "Just as characters are composed of bits, these are composed of characters or bytes.": "fields",
    "Type the method command that displays formatted data on the screen.": "System.out.printf();",
    "Digits, letters, and special symbols are known as...": "characters",
    "Enables a program to read data for use in a program.": "Scanner",
    "Java allows you to assemble string objects into larger strings by using operators + or +=. This is known as...": "string concatenation",
    "How many repetition statements does Java provide that enable programs to perform statements repeatedly as long as a condition remains true?": "four - while, do while, for, enhanced for",
    "Method for square root of x": "sqrt(x)",
    "Method for x raised to the power of y": "pow(x,y)",
    "Method for smaller value of x and y": "min(x,y)",
    "Method for larger value of x and y": "max(x,y)",
    "How many bytes = 1 kilobyte?": "1024",
};

export default JAVATERMS;